analyze/urls.py
from django.conf.urls import url
from . import views

app_name = 'analyze_app'

urlpatterns = [
    url(r"^type/",views.selChart, name='sel_type'),
    url(r"^plot/(?P<type>\w+)/", views.plot, name='plot_graph')
]

app/urls.py
from django.conf.urls import url
from . import views
app_name = 'app'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^fileupload/', views.fileUpload, name='app_file_upload'),
]

forecast/urls.py
from django.conf.urls import url
from . import views

app_name='forecast_app'

urlpatterns=[
    url(r'^forecast/fileupload/', views.fileUpload, name='file_upload'),
    url(r'^forecast/', views.forecast, name='forecast'),
    url(r'^tarselect/', views.targetSel, name='target_Sel'),
    url(r'^view/', views.selView, name='selections_view'),
    url(r'^selections/', views.selection, name='select_view'),
]

xaon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls')),
    url(r'^analyze/',include('analyze.urls')),
    url(r'^forecast/', include('forecast.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/index.html
{% extends "layout.html" %}

{% block content %}
<h2>{{ title }}.</h2>
you are in home
{% endblock %}

app/templates/app/twoway.html
{% extends "layout.html" %}

{% block content %}


 <a href="{% url 'forecast_app:select_view' %}"><button type="button" class="btn btn-info btn-lg" >Forecast</button></a>
 

 <a href="{% url 'analyze_app:sel_type' %}" ><button type="button" class="btn btn-info btn-lg" >Analyze</button></a>

{% endblock %}

app/templates/app/upload.html
{% extends "layout.html" %}

{% block content %}
 <h1>New File</h1>
<form  method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success btn-lg" >Save</button>
</form>

{% endblock %}